BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS `Utilisateur_ListeMenus` (
	`Utilisateur`	INTEGER,
	`ListeMenus`	INTEGER,
	FOREIGN KEY(`Utilisateur`) REFERENCES `Utilisateur`,
	FOREIGN KEY(`ListeMenus`) REFERENCES `ListeMenus`,
	PRIMARY KEY(`Utilisateur`,`ListeMenus`)
);
CREATE TABLE IF NOT EXISTS `Utilisateur` (
	`ID`	INTEGER PRIMARY KEY AUTOINCREMENT,
	`Nom`	TEXT
);
CREATE TABLE IF NOT EXISTS `Tag` (
	`ID`	INTEGER PRIMARY KEY AUTOINCREMENT,
	`Label`	TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS `Repas_Plat` (
	`repas`	INTEGER,
	`plat`	INTEGER,
	FOREIGN KEY(`repas`) REFERENCES `Repas`,
	PRIMARY KEY(`plat`,`repas`),
	FOREIGN KEY(`plat`) REFERENCES `Plat`
);
CREATE TABLE IF NOT EXISTS `Repas` (
	`ID`	INTEGER PRIMARY KEY AUTOINCREMENT,
	`Nom`	TEXT
);
CREATE TABLE IF NOT EXISTS `Plat_Tag` (
	`plat`	INTEGER,
	`tag`	INTEGER,
	FOREIGN KEY(`tag`) REFERENCES `Tag`,
	FOREIGN KEY(`plat`) REFERENCES `Plat`,
	PRIMARY KEY(`tag`,`plat`)
);
CREATE TABLE IF NOT EXISTS `Plat_Ingredient` (
	`plat`	INTEGER,
	`ingredient`	INTEGER,
	`grammes`	INTEGER,
	FOREIGN KEY(`ingredient`) REFERENCES `Ingredient`,
	PRIMARY KEY(`plat`,`ingredient`),
	FOREIGN KEY(`plat`) REFERENCES `Plat`
);
CREATE TABLE IF NOT EXISTS `Plat` (
	`ID`	INTEGER PRIMARY KEY AUTOINCREMENT,
	`intitule`	TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS `Menu_Repas` (
	`menu`	INTEGER,
	`repas`	INTEGER,
	`numero`	INTEGER NOT NULL,
	`personnes`	INTEGER NOT NULL,
	FOREIGN KEY(`menu`) REFERENCES `Menu`,
	PRIMARY KEY(`repas`,`menu`),
	FOREIGN KEY(`repas`) REFERENCES `Repas`
);
CREATE TABLE IF NOT EXISTS `Menu` (
	`ID`	INTEGER PRIMARY KEY AUTOINCREMENT,
	`Nom`	TEXT NOT NULL,
	`Date`	INTEGER NOT NULL
);
CREATE TABLE IF NOT EXISTS `ListeMenus_Menu` (
	`ListeMenus`	INTEGER,
	`Menu`	INTEGER,
	FOREIGN KEY(`ListeMenus`) REFERENCES `ListeMenus`,
	FOREIGN KEY(`Menu`) REFERENCES `Menu`,
	PRIMARY KEY(`ListeMenus`,`Menu`)
);
CREATE TABLE IF NOT EXISTS `ListeMenus` (
	`ID`	INTEGER PRIMARY KEY AUTOINCREMENT,
	`date_debut`	INTEGER NOT NULL,
	`date_fin`	INTEGER NOT NULL
);
CREATE TABLE IF NOT EXISTS `Ingredient` (
	`Nom`	TEXT NOT NULL,
	`ID`	INTEGER PRIMARY KEY AUTOINCREMENT
);
INSERT INTO `Ingredient` VALUES ('Test',1);
COMMIT;
